name: Build installer

on:
  workflow_dispatch: # Allows the workflow to be run manually

jobs:
  build:
    runs-on: windows-2022 # Sets the build environment to run on the latest Windows version

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set variables
      id: asub_env
      run: |
        $file_text = Get-Content "new.txt"
        echo "::set-output name=version::$file_text"

    - name: Setup Python
      uses: actions/setup-python@v4.7.1
      with:
        python-version: 3.11

    - name: Install dev dependencies
      run: |
        pip install -r requirements.dev.txt

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Build
      run: |
        .\scripts\release\build.bat

    - name: Pack
      run: |
        .\scripts\release\pack.bat

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        name: ${​​​​​​​​​{​​​​​​​​​ steps.asub_env.outputs.version }​​​​​​​​​}​​​​​​​​​
        files: .\dist\asub_installer_inno.exe
